version: "3.3"

services:

  pgsql:
    container_name: dcp-pgsql
    image: postgres
    #restart: always
    user: "$UID:$GID"
    volumes:
     - ./postgres/data:/var/lib/postgresql/data
    
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=admin  # senha padrão
      - POSTGRES_USER=postgres  # usuário padrão
      - POSTGRES_DB=postgres  # necessário porque foi configurado assim no settings
     #- PGDATA=pgdata
    ports:
      - 5432:5432  # repare na porta externa 5431
    networks:
      - dcp


volumes:
  pgsql:
  
networks:
  dcp:

